base_url = "https://bear-steps.com"
title = "Bear Steps"
description = "Promoting safe airsteps practice in the aerials community"

compile_sass = false
build_search_index = false
minify_html = false
generate_feeds = false
